Class {
	#name : #C2VStubClass1,
	#superclass : #Object,
	#instVars : [
		'ivar1'
	],
	#category : #'Code2Vec-Base'
}

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m1 [
	16
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m10 [
	[ ]
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m11 [
	[ :arg1 | ]
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m12 [
	[ | temp1 | ]
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m13 [
	[ 1 ]
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m14 [
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m15 [
	self
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m16 [
	super
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m17 [
	self foo1: 'arg1'; foo3
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m18 [
	self foo 
		bar; 
		zork
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m19 [
	#(1 2 3 4)
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m2 [
	16 + 33
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m20 [
	{ivar1. 2}
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m3 [
	ivar1
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m4 [
	ivar1 := 'foo'
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m5 [
	| temp1 |
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m6 [
	| temp1 |
	temp1
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m7: arg1 [
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m8: arg1 [
	arg1
]

{ #category : #'as yet unclassified' }
C2VStubClass1 >> m9 [
	^ 45
]
